### ISSUE TITLE
The 'Refresh' event isn't generated on Windows

### ISSUE THREAD

**Issue by vanderlokken** [tomaka/winit#180]
There is the 'WM_PAINT' window message which Windows sends to an application when its window needs to be redrawn. Logically this message should be processed and the 'winit::WindowEvent::Refresh' event should be emitted as a consequence.

**Comment by LPGhatguy** [comment]
I'm going to try to tackle this.

**Comment by LPGhatguy** [comment]
The actual snippet to handle `WM_PAINT` is really simple:

```rs
winapi::WM_PAINT => {
    use events::WindowEvent::Refresh;
    send_event(window, Refresh);
    0
},
```

However, this event still isn't ever raised because winit doesn't invalidate the render surface. After talking with WindowsBunny on #rust-gamedev, responding to `WM_PAINT` in game-like applications is unusual.

In order to get Windows to raise `WM_PAINT` (and `WM_NCPAINT`), we would need to probably implement an API to explicitly invalidate the window contents, analogous to Win32 `InvalidateRect`.

**Comment by GuildMasterInfinite** [comment]
`WM_PAINT` is not meant to be used by a game-like application, rather by GUI applications that use something like GDI to paint their window.

The fact that `WM_PAINT` is rarely, if ever, sent is a good thing - the OS tries to reduce the need to repaint an application. Windows uses a lot of tricks to reduce the amount of times `WM_PAINT` is sent. 

On older versions, `WM_PAINT` was sent each time the window was hidden and then reshown. Nowadays Windows saves the painted window and repaints it later.

I do believe @LPGhatguy implementation of the `Refresh` event is good, since it works exactly as Windows intended it.

For example, on X11, `Refresh` is caused by the `Expose` which is called only when the window is created or the surface of the window has been lost - which, on modern computers, means very rarely.

**Comment by tomaka** [comment]
I think that's how `Refresh` was designed. In other words, receiving a `Refresh` event means that you are strongly encouraged to redraw. However you shouldn't draw only when you receive these events.
