### ISSUE TITLE
Type errors in unix::WindowExt for X11

### ISSUE THREAD

**Issue by vberger** [tomaka/winit#256]
The `get_xlib_window` returns a value that is defined by the X11 API to be `Wffi::indow` (which is a typedef to `c_ulong`), but casts it to `*mut c_void`.

Likewise, `get_xlib_screen_id` returns a value defined by the X11 API to be a `c_int`, but casts it to `*mut c_void`.

My understanding of the X11 API is very light, but this seems wrong to do so, especially given depending on the architecture, these types are not guaranteed to even be the same size.

Do you have some insight regarding this @Ralith ? (pinging you as you seem to have a fair amount of knowledge of X11)

**Comment by francesca64** [comment]
When `get_xlib_window` is [used by glutin](https://github.com/tomaka/glutin/blob/f7e4e1a94e8c0cd81f4a6956d48a5b02cb54320e/src/platform/linux/x11.rs#L213), it's either cast right back to `ffi::Window` ([here](https://github.com/tomaka/glutin/blob/61e9ada5aeaf0ec609b7646f36d4de2fb8d016e7/src/api/glx/mod.rs#L185)) or used as [`ffi::EGLNativeWindowType`](http://nercury.github.io/egli-rs/egli/egl/type.EGLNativeWindowType.html) to later be passed to [`eglCreateWindowSurface`](https://github.com/mesa3d/mesa/blob/a1b4f1877f2ef7f0e1e10fdcef854391547f1018/src/egl/drivers/dri2/platform_x11.c#L213) ([here](https://github.com/tomaka/glutin/blob/f7e4e1a94e8c0cd81f4a6956d48a5b02cb54320e/src/api/egl/mod.rs#L367)). Looking at [the official example](https://www.khronos.org/registry/EGL/extensions/EXT/EGL_EXT_platform_x11.txt), that function does expect the window ID, so casting the value itself into a pointer does seem to be correct, albeit unintuitive, since it's being used for type erasure.

While `ffi::Window` isn't guaranteed to be pointer-sized, I can't imagine it will ever be larger, and as far as I can tell [Rust treats these pointer conversions just like it would any ordinary integer cast](https://play.rust-lang.org/?gist=7ddc42aeeacc09be3284244231cc83a0&version=stable). In other words, this should always work.

**Comment by Ralith** [comment]
Sorry, this must have slipped through the cracks. I don't know of any reason why we shouldn't be using the proper C types here; it seems we're only getting away with it by coincidence.
