### ISSUE TITLE
Getting ReceivedCharacter after KeyboardInput

### ISSUE THREAD

**Issue by paulrouget** [tomaka/winit#268]
This is at least true on osx.

When getting KeyboardInput with a pressed state, we want to look up the last received character. So it's important to receive ReceivedCharacter before KeyboardInput.

This used to be the case.

**Comment by jwilm** [comment]
What can you do with that ordering that's not possible with the current ordering? In order to provide a guaranteed ordering across platforms, the current ordering is required (you can thank Windows).

Current ordering is

* `KeyboardInput` (press)
* `ReceivedCharacter` (0 or more)
* `KeyboardInput` (release)

Or in the case of repetition,

* `KeyboardInput` (press)
* `ReceivedCharacter` (0 or more)
* `KeyboardInput` (press)
* `ReceivedCharacter` (0 or more)
* ...
* `KeyboardInput` (release)

It sounds like you could achieve the same behavior as before by buffering received chars and waiting until the next `KeyboardInput` event (press or release). What is the use case anyway? Maybe we could help you identify an alternative solution given the constraints here?

**Comment by paulrouget** [comment]
Thank you.

In servo, when getting pressed event, we want to display the associated character. It's always been a bit hairy. See https://github.com/servo/servo/blob/master/ports/glutin/window.rs#L417

So on KeyboardInput (press) we send the key event to Servo. But it's missing the character.

We can't really send the event on `ReceivedCharacter` because we're not always sure to get this event.

Does it make sense?

**Comment by jwilm** [comment]
How is that supposed to work when multiple characters are received? It looks like your received character handler always overrides the already cached value.

**Comment by paulrouget** [comment]
> How is that supposed to work when multiple characters are received?

iirc, we just take the last one. I know it's not optimal, but until we get proper IME support, we need something minimal to work.

In an older version of glutin, we would:

- get ReceivedCharacter, store character
- get KeyboardInput (press), send event to servo with store character

We can't do that anymore because ReceivedCharacter happens after.

We could store the event state on KeyboardInput and send event to servo on ReceivedCharacter, but if I'm not mistaken, we never guaranteed that ReceivedCharacter will be fired.

**Comment by jwilm** [comment]
Is there an issue with the windows implementation in the file you linked? It's already set up to work with the current event ordering.

**Comment by paulrouget** [comment]
Oh I see. Now it works like on Windows for MacOS and Linux.

So I need to store the modifiers on keyboardinput, and send message on both ReceivedCharacter and keyboardinput.

That should do it.

Thank you!

**Comment by jwilm** [comment]
> Now it works like on Windows for MacOS and Linux.

Yep! Unless I'm missing something, it kind of seems like the conditional compilation could be dropped in favor of using the current windows implementation for all platforms.

**Comment by paulrouget** [comment]
It works.
