### ISSUE TITLE
[Backends] State of Send + Sync in winit

### ISSUE THREAD

**Issue by vberger** [tomaka/winit#320]
I'm starting to work on a large rework of the wayland backend (again!) to port it to the new wayland-client API, hopefully simplifying it a little in the process.

Now, There is a question that it raises for me: what constraints do we put on whether `Window` and `EventsLoop` are `Send` and or `Sync` ?

I've seen at some point a test to ensure that `EventsLoop` was `Send + Sync`, but it seems this test has been removed now. Overall, I see at least some backends are `Send + Sync`, but with the numerous API changes that occurred during the last months, I've lost track of this point.

So:

- is `Window` supposed to be `Send` and/or `Sync` ?
- is `EventsLoop` supposed to be `Send` and/or `Sync` ?

**Comment by mitchmindtree** [comment]
If winit should always behave consistently across platforms, `EventsLoop` really should not be `Sync` or `Send` due to macos' requirement of polling/waiting on events on the main thread (at least, I never worked out a nice way around this). I'd go as far as making `EventsLoop` main-only if there was some way to do so. I'm less sure about the behaviour for `Window`s.

**Comment by Ralith** [comment]
I don't think there's a good reason for it to be `Sync`; this substantially complicates implementation for little practical benefit. IIRC we've discussed this before and came to the same conclusion.

**Comment by alexheretic** [comment]
I currently I rely on `Send` for `EventsLoop`.

**Comment by mitchmindtree** [comment]
@alexheretic could you elaborate on your use case for `EventsLoop` being `Send`?

**Comment by alexheretic** [comment]
Sure, I have a separate compute and render threads which don't block each other. Since compute processes events, `EventsLoop` is sent away from `Window` which resides on the render thread.

Without it I'd have to process events on, and presumably delayed by, the rendering thread and send the events over to the compute, which would be much more of a pain for me.

**Comment by vberger** [comment]
@alexheretic So, I guess having for example, the EventsLoop not Send, but the Window being Send would work for you as well?

**Comment by alexheretic** [comment]
@vberger Yes I believe so.

**Comment by vberger** [comment]
So, I tend to lean that way too. Currently with wayland, all is Send+Sync, but it substantially complicates the implementation (and will be even more problematic if I try to upgrade to the next version of wayland-client).

Given what @mitchmindtree said, it appears there are platforms for which having the `EventsLoop` being `Send` and/or `Sync` is a complicated matter.

I'd argue that being consistent across platforms is important, and that in this case we should impose that `EventsLoop` is `!Send` and `!Sync` (possibly via a PhantomData marker, or something like that).

On the other hand, if this is chosen, this means that we need to make `Window` at least `Send`, if  possible.

**Comment by vberger** [comment]
Done in #322 .
