### ISSUE TITLE
get_inner_size() does not return physical pixels on MacOS

### ISSUE THREAD

**Issue by jrmuizel** [tomaka/winit#399]
I believe it is intended to do so.

**Comment by kvark** [comment]
In the code:
```rust
    #[inline]
    pub fn get_inner_size(&self) -> Option<(u32, u32)> {
        unsafe {
            let view_frame = NSView::frame(*self.view);
            Some((view_frame.size.width as u32, view_frame.size.height as u32))
        }
    }
```
So the size on OSX is taken from the `NSView`, which is logical pixels. If physical pixels are needed (for passing into `glViewport` as the docs say), then one should be calling [convertRectToBacking](https://developer.apple.com/documentation/appkit/nsview/1483648-convertrecttobacking?language=objc). Unfortunately, it doesn't appear to be hooked up in the current [cocoa bindings](http://lux.graphics/doc/cocoa/appkit/trait.NSView.html) so that could be a start.

However, it would be great to clarify the semantics of the inner size clearly first. For example, `set_inner_size` doesn't make much sense if it's in the physical pixels, since the window sizes are provided in logical (although, we could convert).

**Comment by anderejd** [comment]
A type LogicalPixels and a PhysicalPixels would be nice instead of the u32 tuple.
