### ISSUE TITLE
Delta for scroll events is calculated incorrectly in case window lost and gained focus again

### ISSUE THREAD

**Issue by synaptiko** [tomaka/winit#447]
Please see the description in https://github.com/jwilm/alacritty/issues/1185, there are steps to reproduce and analysis of what is happening.

According to @jwilm's findings the issue seems to be located here:
https://github.com/tomaka/winit/blob/51181b4347aed6f7c1a384c6810635bd6801b369/src/platform/linux/x11/mod.rs#L609

**Comment by francesca64** [comment]
I haven't been able to reproduce this so far. When the window is entered, the mouse wheel position should be reset: https://github.com/tomaka/winit/blob/1c4973d5b73de174a57d51de4f7cf6fc12525415/src/platform/linux/x11/mod.rs#L688-L693

I can reproduce this if I comment out that call, so I'm thinking the problem is probably one of three things:
1. The `XI_Enter` event's `sourceid` isn't corresponding to the device ID of whatever's scrolling.
2. The `XI_Enter` event isn't being triggered.
3. The implementation of `reset_scroll_position` is wrong.

I see №1 as the most likely, especially since in my own testing, I would sometimes get a `sourceid` of 2 (the core virtual pointer ID) as opposed to the ID of my specific device. When that happens, no resetting will happen, though under Xfwm4 I only get 2 when the "new window" autofocus kicks in, so it's not an issue there (it also happens when I'm holding down alt to drag the window around, but I've not been able to begin scrolling in the window without triggering an `XI_Enter` of the relevant ID, so it doesn't matter). Looking at the original issue, it seems that i3 is a common element between people who could reproduce this, so I'm going to test there.

**Comment by synaptiko** [comment]
@francesca64 Thank you so much for diving into this. It could be related to the way how i3 is switching workspaces. Maybe it's actually a bug in i3 if it doesn't happen in other DEs.

But under i3 it's 100% reproducible for me. If there is a way I could help you debug this let me know…

**Comment by BurntSushi** [comment]
@synaptiko The specific bug in Alacritty happens for me as well, and I don't use i3. (I use my own WM.)

**Comment by francesca64** [comment]
I'm not able to reproduce this using i3 4.15. Here's a branch that prints some debug info: https://github.com/francesca64/winit/tree/x11-scroll-reset

**Comment by francesca64** [comment]
I seem to have found the solution. You can try it out here: https://github.com/francesca64/alacritty/tree/scroll-debug

Thanks to @carado for testing this!

@BurntSushi the problem is caused by `XI_Enter` having the `sourceid` set to the virtual device ID. I'm not sure how responsible WMs are for things like that, but it's not the behavior I'd expect.

**Comment by BurntSushi** [comment]
@francesca64 Awesome, thank you! :D
