### ISSUE TITLE
Windows: winit DeviceEvent for KeyboardInput does not work

### ISSUE THREAD

**Issue by hobogenized** [tomaka/winit#467]
DeviceEvents for KeyboardInput don't seem to be working on Windows. My friend on Linux seems to have no issue with it.

A sample program to reproduce the issue:
```
extern crate winit;

fn main() {

    let mut events = winit::EventsLoop::new();
    let window = winit::Window::new(&events);
    
    while true {
        let mut keypressed = false;
        events.poll_events(|event| {
            match event {
                winit::Event::DeviceEvent {
                    event: winit::DeviceEvent::Key(KeyboardInput),
                    .. 
                } => {
                    eprintln!("Key pressed");
                },
                _ => {}
            }
        });
    }
}
```

**Comment by francesca64** [comment]
I believe I've finished implementing this, if you'd like to try the branch: https://github.com/francesca64/winit/tree/win-device-events

I excluded `DeviceEvent::Key`, since there doesn't seem to be any practical way to implement that to give you the same characters you'd expect from `WindowEvent::ReceivedCharacter`.

**Comment by hobogenized** [comment]
Confirming that it works with the example code I posted above. Hope that branch gets merged soon.
