### ISSUE TITLE
set_cursor_state(CursorState::Grab) not working correctly on Windows 8.1

### ISSUE THREAD

**Issue by Boscop** [tomaka/winit#523]
When I call `display.gl_window().window().set_cursor_state(CursorState::Grab)` every frame, at first it works, the cursor is hidden and can't be moved out of the window with the mouse.
But I can still ALT+TAB out of the Window, and then, when I move the cursor back over the window, it's not being grabbed even though I call that function every frame!
After that it behaves like `Hide`, i.e. the cursor is hidden while over the window, but it's not grabbed.

**Comment by francesca64** [comment]
I'd assume this is caused by winit's cursor state being stale, so it probably just no-ops every time due to winit thinking it's still grabbed.

The simplest solution is just to query the state each time using [`GetClipCursor`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms648387(v=vs.85).aspx), though the entire `set_cursor_state` function could use some cleanup.
