### ISSUE TITLE
with_resizable / set_resizable

### ISSUE THREAD

**Issue by dannyfritz** [tomaka/winit#540]
Be able to disable resizing of the window. This would include removing the resize cursors when hovering over the edge of the window.

Related to #65 and https://github.com/tomaka/glutin/issues/877

|                        | Windows | X11 | Wayland | MacOS | iOS | Emscripten | Android |
| --------------- | -----------| ---- | ----------| ---------| --- | ------------ | --------- |
| `with_resizable` | ✔#541 | ✔#556 | ✔ #565 | ✔#553 | NA | NA | NA |
| `set_resizable`   | ✔#558 | ✔#558  | ✔ #565 | ✔#553 | NA | NA | NA |

**Comment by francesca64** [comment]
Thanks for reporting this. AFAIK this should be straightforward to implement on X11, Windows, and macOS.

@vberger is this possible on Wayland?

**Comment by dannyfritz** [comment]
I'm playing around with this to see if I can get it to work for Windows. Removing `WS_SIZEBOX` from the `styles` seems to mess up a lot more than just preventing resizing.

**Comment by vberger** [comment]
Right now it is already doable (I believe on all platforms) by setting a min_size and max_size, both with the same values.

It'll require some work on smithay's client toolkit to remove the "resize" cursor hint from the decorations as well on wayland, but it should not be a big thing.

**Comment by dannyfritz** [comment]
I made [a commit to attempt `X11`](https://github.com/dannyfritz/winit/commit/50ba0fdb90d16bd610b15f11946481785e2c50f2), I haven't played around with it too much, but it seems using `_NET_WM_ALLOWED_ACTIONS` and `_NET_WM_ACTION_RESIZE` isn't having any effect.

**Comment by dannyfritz** [comment]
[Here](https://github.com/dannyfritz/winit/commit/ad3f52adb91a14ab12d2499c0ffd08175e283b4a) is where I'm at now.

It crashes intermitedly with a `TypeMismatch(0)` Error from `xconn::get_property`.
I'm not sure if it is just my X11 server, but when it does successfully run without erroring and removes `_NET_WM_ACTION_RESIZE`, it doesn't seem to take hold as I can still resize the window.

---

`ffi::XA_ATOM` took me the longest time to figure out. I was doing this for the longest time:

```rust
let array_atom = unsafe { self.xconn.get_atom_unchecked(b"ATOM[]\0") };
```

**Comment by francesca64** [comment]
Checking with `xprop _NET_WM_ALLOWED_ACTIONS`, I can confirm that the hint is correctly removed, so good job. I don't get any errors, but I think I know the problem with that - X11 doesn't have some federated awareness of these properties, so if the property is initially unset, then the property's type is `None` (the X11 atom `None`, which is always 0; I should probably change `TypeMismatch(Atom)` to `TypeMismatch { actual_type: Atom, expected_type: Atom }`, and change the `Debug` impl to fill in the atom names, along with specially handling this case and returning `Result<Option<Vec<T>>, GetPropertyError>`). 

In that case, you'd have to supply the default list yourself, but I guess that doesn't matter anymore. The window is resizable for me too.

> `ffi::XA_ATOM` took me a while to figure out

Ha, yeah. X11 specs tend to exclude concrete details like that, since part of the philosophy is to be implementation-agnostic. On the bright side, at least it wasn't cardinals. Never once have I succeeded in finding *any* resource that explains what X11 cardinals are; it's just sort of understood (from looking through source code) that cardinals are longs.

winit's codebase is a good reference for this stuff, at least compared to picking through the source code of GTK/etc. At some point I'd like to make things more strongly typed, so you'd instead do something like `xconn.get_property(window, NetWm::AllowedActions)`. I'm sure what you really would've wanted was documentation, though.

> it seems `_NET_WM_ALLOWED_ACTIONS` exists to tell other apps what your window is capable of

The language in the spec isn't the easiest to interpret (that tends to be the biggest issue when working with X11, actually). My current takeaway is that using this hint would result in the WM no longer honoring [`_NET_MOVERESIZE_WINDOW`](https://specifications.freedesktop.org/wm-spec/1.4/ar01s04.html) for that window, which, as you said, would only be sent by other apps.

> I can confirm setting the min/max for my X11 instance works as I would want it to; no cursors and no resizing.

Great! If it works, then it works. The WM hints spec also implied that this is the recommended way for WMs to detect that a window isn't resizable, so it sounds good to me. Sorry for sending you down the wrong path.

**Comment by francesca64** [comment]
I want to release 0.15.1 tomorrow, so it looks like `set_resizable` will have to wait for 0.16.0. It's still a good idea to get `with_resizable` setting the min/max to equal on Wayland before that; I'll do that if no one else has a chance to.
