### ISSUE TITLE
Improve / remove inital dpi resizing

### ISSUE THREAD

**Issue by alexheretic** [tomaka/winit#581]
Based on the short conversation in https://github.com/gfx-rs/gfx/pull/2188 this may not be practical to fix, but I thought it could be useful to provide an example of the current behaviour just in case we can improve.

Basically if you want to set the window to a physical size and the dpi is not 1.0 you currently have to wait for 2 resize events. This feels a bit weird.

## Example (X11)
```rust
#[macro_use]
extern crate log;
extern crate env_logger;
extern crate winit;

fn main() {
    env_logger::init();

    let mut events = winit::EventsLoop::new();
    let hidpi = events.get_primary_monitor().get_hidpi_factor();

    info!("hidpi: {:?}", hidpi);

    let window = winit::WindowBuilder::new()
        .with_dimensions(winit::dpi::PhysicalSize::new(800.0, 600.0).to_logical(hidpi))
        .build(&events)
        .unwrap();

    info!(
        "window size: {:?} {:?}",
        window.get_inner_size(),
        window.get_inner_size().map(|s| s.to_physical(hidpi))
    );

    let mut resizes = 0;
    while resizes < 2 {
        events.poll_events(|event| {
            if let winit::Event::WindowEvent {
                event: winit::WindowEvent::Resized(size),
                ..
            } = event
            {
                resizes += 1;
                info!("resize: {:?} {:?}", size, size.to_physical(hidpi));
            }
        });
    }

    info!(
        "window size: {:?} {:?}",
        window.get_inner_size(),
        window.get_inner_size().map(|s| s.to_physical(hidpi))
    );
}
```
```
INFO 2018-06-28T18:23:11Z: rusttmp: hidpi: 1.1666666666666667
INFO 2018-06-28T18:23:11Z: rusttmp: window size: Some(LogicalSize { width: 588.0, height: 440.57142857142856 }) Some(PhysicalSize { width: 686.0, height: 514.0 })
INFO 2018-06-28T18:23:11Z: rusttmp: resize: LogicalSize { width: 588.0, height: 440.57142857142856 } PhysicalSize { width: 686.0, height: 514.0 }
INFO 2018-06-28T18:23:11Z: rusttmp: resize: LogicalSize { width: 685.7142857142857, height: 514.2857142857142 } PhysicalSize { width: 800.0, height: 600.0 }
INFO 2018-06-28T18:23:11Z: rusttmp: window size: Some(LogicalSize { width: 685.7142857142857, height: 514.2857142857142 }) Some(PhysicalSize { width: 800.0, height: 600.0 })
```

This means that if you use the window size after creation it will use incorrect data. Even assuming all users handle resizes properly this means wasted effort at startup that could be expensive depending on application.

**Comment by francesca64** [comment]
> Basically if you want to set the window to a physical size and the dpi is not 1.0 you currently have to wait for 2 resize events. This feels a bit weird.

Why would you want to create a window using a physical size?

Even if I did change that, you'd then have the opposite problem on macOS and Wayland.

**Comment by francesca64** [comment]
Oh, I should mention. There's a completely sound way to fix this, and that would be the ability to create a window on a specific monitor (or to more generally know the destination monitor in advance). However, I'm not sure how feasible that is to implement and what the UX implications of allowing that would be (versus allowing the WM to choose).

The ideal solution on X11 would be if the WM implemented some sort of protocol that informed us of where a new window of WxH dimensions would be placed, but such a protocol likely doesn't exist (due to various complications with async/etc.)

**Comment by alexheretic** [comment]
> Why would you want to create a window using a physical size?

Hmm seems like a reasonable thing to want to do. Like creating a window to show an image at it's exact size.

But forget the physical stuff, it's the starting at the wrong size then resizing to the right one that seems bad.

**Comment by alexheretic** [comment]
> know the destination monitor in advance.

Maybe we can add an optimisation for single-monitor environments then?

**Comment by francesca64** [comment]
That would work (and be trivial to implement), and the same optimization could be used with multiple monitors that all have the same DPI.

**Comment by alexheretic** [comment]
Well that sounds promising!

**Comment by francesca64** [comment]
Alright, I'm in the process of implementing this on X11, and I've got some good news: since (at least on my WM; I don't have enough free VRAM to check other WMs right now) the window is mapped on the monitor that the cursor is on, I can reliably guess the correct DPI even in mixed-DPI environments.

Checking if all monitors have the same DPI (which covers the single monitor case) is still the first thing that's tried, and even if the cursor guess is wrong, all that will happen is that it falls back to the existing behavior. Still, this will likely remove the issue for the majority of people on X11.

I still need to check out the heuristics on Windows, but I'm confident I'll be able to make a similar level of improvement there.

**Comment by alexheretic** [comment]
Nice one! This seems like a improvement for all, using the cursor to guess is a good idea. I can test on gnome & windows if that's helpful.

**Comment by francesca64** [comment]
Here's the X11 PR, if you want to try it out: #583

**Comment by francesca64** [comment]
The situation on Windows is a bit more unfortunate... when opening from PowerShell or bash/mintty, it seems to always open on the primary monitor. When opening from the taskbar, it opens on whichever monitor the taskbar is on (though most apps actually have logic to re-open on the monitor they were closed on).

I suppose the best trade-off is to just use the cursor position again, since chances are that you'll have the terminal on the same monitor as where the windows show up, and the end-user experience is more critical than the developer experience.
