### ISSUE TITLE
get_hidpi_factor returns incorrect value for Gnome on Wayland

### ISSUE THREAD

**Issue by newpavlov** [tomaka/winit#594]
In wayland `get_hidpi_factor` returns 1.0 instead of the correct value equal to 2.0. I am using Gnome 3.28.2 and winit v0.16.1.

**Comment by francesca64** [comment]
You're possibly hitting the `unwrap_or` case: https://github.com/tomaka/winit/blob/c873c2db1508bb420e7fa0518e6727c31154e1b8/src/platform/linux/wayland/event_loop.rs#L475-L479

From the looks of things, the value itself comes from upstream: https://github.com/Smithay/client-toolkit/blob/269f3ea95c9cdf15b0311ccaa295c68a11bea43b/src/output.rs#L55

**Comment by newpavlov** [comment]
No, does not look like it. I've replaced `get_hidpi_factor` body with the following code:
```Rust
self.mgr
    .with_info(&self.proxy, |_, info| {
        println!("with_info");
        info.scale_factor
    })
    .unwrap()
```

It does not result in panic. With the following line in the event loop ((I am using `vulkano`, but I don't think it's relevant)):
```Rust
println!("get_hidpi_factor: {:?}", surface.window().get_hidpi_factor());
```
I am getting this result:
```
get_hidpi_factor: 1.0
get_hidpi_factor: 1.0
get_hidpi_factor: 1.0
with_info
with_info
get_hidpi_factor: 2.0
with_info
get_hidpi_factor: 2.0
```

So it's look like `get_hidpi_factor` gets called quite late for some reason.

**Comment by newpavlov** [comment]
Hm, it looks like I should just catch `HiDpiFactorChanged` event instead of calling `get_hidpi_factor` manually. Is it an intended behavior? If so, then I think it should be documented in the `get_hidpi_factor` docs.

**Comment by francesca64** [comment]
Hm, are you saying that calls to `get_hidpi_factor` made before the event loop runs aren't correct?

**Comment by newpavlov** [comment]
Yes, and several iterations of the event loop as well.

**Comment by francesca64** [comment]
That's definitely weird. That's not the case for X11, Windows, macOS, and iOS, so I'd say this is a bug in our implementation for Wayland.

**Comment by vberger** [comment]
The reason `get_hidpi_factor` is called "quite late" is most likely because before that winit has net yet received the events from the server notifying which monitor(s) the surface is being displayed on.

Before that, the winit window believes it's not displayed on any monitor and hits the fallback as `self.monitors` is empty: https://github.com/tomaka/winit/blob/c1ef1acfc0a6d372519c3cf1a1c1e0696373fa61/src/platform/linux/wayland/window.rs#L428-L435 

I'm not sure what would be the best approach to solve this, it is not possible to blockingly wait for this event at window creation for example, because these events are not send before the window actually exists, which requires that it has been drawn at least once...

We could use a better heuristic for fallback than `1` though, for example taking the maximum of the dpi factors of all available monitors?

**Comment by newpavlov** [comment]
Even without improving the fallback, it could be useful to add recommendation into `get_hidpi_factor` docs to track `HiDpiFactorChanged` event.

I think this issue can be closed, of course if you don't think it's better to keep it for now.
