### ISSUE TITLE
iOS should be able to support Metal as well as OpenGLES

### ISSUE THREAD

**Issue by mtak-** [tomaka/winit#596]
I would like to help get the ball rolling on this. I have a [branch](https://github.com/BrainiumLLC/winit/tree/ios_metal_support) with relevant changes [here](https://github.com/BrainiumLLC/winit/commit/e803715f0c8936539c863a2a3c8882e2a149d9f0) to allow for using Metal as the backend on iOS.

It depends on [this](https://github.com/tomaka/winit/pull/595) PR from earlier today.

I had to modify vulkano [here](https://github.com/BrainiumLLC/vulkano/commit/aef7b39f4145313c186b1804417027400a2a5787) in order to test this out.

I have no idea what the desired way to structure the winit changes is. I'd be grateful for some guidance on this.

**Comment by francesca64** [comment]
You may have noticed that the iOS backend isn't structured very well, especially when taken with the big picture of how it interacts with glutin's iOS backend. That's why I stuck some GL-specific code in the winit backend, since I didn't have the energy for a complete restructuring of both at the time.

Ideally, winit should contain no graphics API-specific logic, so the ideal here is to lift the GL stuff into glutin and make sure 1) everything is initialized in the correct sequence, and 2) a mechanism exists for winit to know to use the proper view subclass/etc. I'd imagine the Metal stuff should live in `vulkano-win`?

**Comment by mtak-** [comment]
Thank you for the feedback. I think that restructuring makes sense, and it sounds like a decent chunk of work.

I will be poking at this in the next week or two, but my priority is to get a demo of vulkano/gfx-rs/glium going on ios to convince my company to try it out.

**Comment by mtak-** [comment]
Here is the pull request. It's a breaking change to the iOS users. Hopefully there aren't too many?

#609

**Comment by francesca64** [comment]
Fixed via #609
