### ISSUE TITLE
[Linux] Multiple monitors identified as a single one

### ISSUE THREAD

**Issue by tomaka** [tomaka/winit#64]
Original: https://github.com/tomaka/glutin/issues/678

**Comment by jwilm** [comment]
It looks like `get_available_monitors` should actually return a list as expect now. However, `get_current_monitor` doesn't work properly. The problem seems to be that the value it's using for current position is the position *within the current monitor*, rather than its absolute position within the X screen.

**Comment by francesca64** [comment]
> The problem seems to be that the value it's using for current position is the position within the current monitor

I don't know what the specific problem was, but the entire `get_current_monitor` function looked super messy, so I rewrote the entire thing. It works now, so this will be resolved quite soon.
