### ISSUE TITLE
Full Screen Focus Switch OSX

### ISSUE THREAD

**Issue by tomaka** [tomaka/winit#66]
Original: https://github.com/tomaka/glutin/issues/720

**Comment by mitchmindtree** [comment]
Can confirm this behaviour on OS X 10.10.5. Even when dragging other windows or opening new windows on top of the fullscreen window, the fullscreen window always remains on top despite losing focus.

I think normally fullscreen behaviour on OS X opens a new "desktop" tab for the fullscreen window so that it can occupy its own desktop entirely, allowing the user to swipe left and right between their existing desktop and the new desktop with their fullscreen window. Haven't had a chance yet to look at the current fullscreen behaviour to know what's going on.

Curiously, when running the fullscreen.rs example with two monitors, the window is always open on the monitor which was focused when the example is run, despite which monitor is selected on the command line. Here's an example where I run the example on my larger monitor while selecting my smaller monitor on the command line prompt:

![screen shot 2016-11-24 at 1 29 45 pm](https://cloud.githubusercontent.com/assets/4587373/20584792/2d15921e-b24a-11e6-8d20-43fae533f505.png)

The dimensions of the smaller monitor are used, while still displaying the "fullscreen" window on the larger monitor.

**Comment by francesca64** [comment]
This is now fixed via #465. However, the fullscreen window is still placed on the currently focused monitor, which [will be fixed once the relevant additions are made to core-foundation](https://github.com/tomaka/winit/pull/465#issuecomment-381993288).
