### ISSUE TITLE
Unit testing: Panic messages should not contain control characters

### ISSUE THREAD

**Issue by nausicaea** [tomaka/winit#678]
When writing unit tests for a library that depends on `winit`, I discovered that under certain circumstances, `winit` fails to initialize and panics with a message that is built from a raw string (see [/src/platform/linux/mod.rs](https://github.com/tomaka/winit/blob/master/src/platform/linux/mod.rs#L433-L436)).

This makes cases that trigger such a panic hard to test for (or at the least prone to errors), because the message contains newlines and multiple successive spaces. Depending on how the source of `winit` is edited, those spaces could at some point become `\t` characters, which would make my tests fail, even though functionally, nothing had changed.

I know that this could also be seen as a cosmetic issue, but in my humble opinion, it would be nice to have single-line panic messages that include as few control characters as possible.

Regardless, thank you for this invaluable library!

**Comment by francesca64** [comment]
Oh, I'm sorry! I used the formatting there to try to be fancy, but if it's an inconvenience at all I have no problem with it being removed. I'd gladly accept a PR to that effect; otherwise, I'll change it myself when I get a chance.

**Comment by nausicaea** [comment]
Uhm, I'm a bit unsure on how to proceed. I've never contributed to a project other than my own and I wanted to ask whether there is a procedure that I'm expected to follow when creating a pull request. Do you have any conventions in place (branching, updating the changelog, testing, checklists?)?

**Comment by francesca64** [comment]
(Sorry that this isn't documented anywhere!)
- Creating a separate branch is nice, just because it makes it a bit easier for me to checkout things.
- A changelog entry would be quite nice, and the style/format should match what's already in the changelog.
- You don't really need to worry about testing, at least in this case. If it works correctly for you, works correctly for me, and passes CI, then you're all good.
- The [PR template](https://github.com/tomaka/winit/blob/master/.github/PULL_REQUEST_TEMPLATE.md) includes a little checklist, though only the first two items would apply to this kind of revision.

**Comment by francesca64** [comment]
Fixed via #681
