### ISSUE TITLE
Setting the window icon

### ISSUE THREAD

**Issue by tomaka** [tomaka/winit#69]
Original: https://github.com/tomaka/glutin/issues/771

**Comment by sjaustirni** [comment]
Hi!
I am wondering, has anything been made in this matter? Is there at least an API people could start implementing?

**Comment by isavegas** [comment]
Perhaps the best way to handle it would be a feature flag that uses a crate like [image](https://crates.io/crates/image) and abstracts the icon assignment for whatever window manager you're using. Of course, anything that requires an external image file would require saving to the file at runtime or a ```build.rs``` for it, but it should be possible.

**Comment by icefoxen** [comment]
I'd probably make some sort of system that just takes a simple RGBA bitmap in the form of a `&[u8]` and turns it into whatever platform-specific format is necessary.  It's a bit of a hack I expect but hopefully a very simple hack...

**Comment by icefoxen** [comment]
It's too fiddly to make Windows also take ARGB or something like that? (I
don't know much about Windows.)

**Comment by francesca64** [comment]
To be honest, my main rationale was that the docs for [`CreateIcon`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms648059(v=vs.85).aspx) looked intimidating. Since you asked, I gave it a shot today, and it was actually pretty easy. 

So, now I can provide a consistent API that expects RGBA. I'll also include an example program that demonstrates how to use `image` to set the icon using any image file.

**Comment by francesca64** [comment]
PR is up: #497
