### ISSUE TITLE
Winit doesnt build on linux

### ISSUE THREAD

**Issue by rukai** [tomaka/winit#754]
Winit doesn't build after updating to wayland-client v0.21.9                                                       
```
error[E0004]: non-exhaustive patterns: `Shape { .. }` and `Orientation { .. }` not covered                                                        
  --> /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.18.0/src/platform/linux/wayland/touch.rs:30:19                          
   |                                                                                                                                              
30 |             match evt {                                                                                                                      
   |                   ^^^ patterns `Shape { .. }` and `Orientation { .. }` not covered                                                                             
```

Reported upstream: https://github.com/Smithay/wayland-rs/issues/221

**Comment by rukai** [comment]
vberger said he wont be able to fix it until tomorrow.
As a work around add this to your cargo.toml `wayland-client = "=0.21.7"`

**Comment by artursapek** [comment]
I just ran into this! Thanks for the fix.

**Comment by sunjay** [comment]
I can confirm that running `cargo update` and then compiling makes everything work even without the workaround.

**Comment by rukai** [comment]
thanks @vberger !

**Comment by commitcompanion** [comment]
Description:

I encountered an error while compiling a Rust project using winit version 0.30.7. The error message indicates that the platform is not supported by winit. Here is the error log:

error: The platform you're compiling for is not supported by winit
  --> /home/developer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.7/src/platform_impl/mod.rs:78:1
   |
78 | compile_error!("The platform you're compiling for is not supported by winit...
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0432]: unresolved import `self::platform`
  --> /home/developer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.7/src/platform_impl/mod.rs:34:15
   |
34 | pub use self::platform::*;
   |               ^^^^^^^^ could not find `platform` in `self`

error[E0432]: unresolved imports `crate::platform_impl::PlatformCustomCursor`, `crate::platform_impl::PlatformCustomCursorSource`
 --> /home/developer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.7/src/cursor.rs:8:28
  |
8 | ...::{PlatformCustomCursor, PlatformCustomCursorSourc...
  |       ^^^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^^^^^^^^ no `PlatformCustomCursorSource` in `platform_impl`
  |       |
  |       no `PlatformCustomCursor` in `platform_impl`

error[E0432]: unresolved import `crate::platform_impl::PlatformIcon`
 --> /home/developer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.7/src/icon.rs:1:5
  |
1 | use crate::platform_impl::PlatformIc...
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `PlatformIcon` in `platform_impl`

error[E0432]: unresolved import `crate::platform_impl::PlatformSpecificWindowAttributes`
 --> /home/developer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.7/src/window.rs:7:34
  |
7 | ...f, PlatformSpecificWindowAttribute...
  |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `PlatformSpecificWindowAttributes` in `platform_impl`

error[E0369]: binary operation `==` cannot be applied to type `&std::option::Option<MonitorHandle>`
    --> /home/developer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.7/src/window.rs:1751:16
     |
1746 | ...ne, Debug, PartialEq, Eq)]
     |               --------- in this derive macro expansion
...
1751 | ...ss(Option<MonitorHandle>),
     |       ^^^^^^^^^^^^^^^^^^^^^
     |
     = note: this error originates in the derive macro `PartialEq` (in Nightly builds, run with -Z macro-backtrace for more info)

Steps to Reproduce:

    Clone the repository and navigate to the project directory.
    Run the command: cargo run --release -p egui_demo_app.
    Observe the compilation error as described above.

Expected Behavior:

The project should compile successfully without any platform-related errors.
Additional Information:

    Rust Version: 1.80.0
    winit Version: 0.30.7
    Operating System: Linux

**Comment by rukai** [comment]
Please raise a new ticket for this, it is a seperate issue.

**Comment by madsmtm** [comment]
@commitcompanion: Indeed, please open a new issue, and provide the output from running the command `rustc -vV`

**Comment by kchibisov** [comment]
They opened, and already got their response.
