### ISSUE TITLE
Publish v0.19

### ISSUE THREAD

**Issue by paulrouget** [tomaka/winit#803]
In Servo, we need the new image crate version (0.21).

**Comment by paulrouget** [comment]
With the associated glutin update if possible :)

**Comment by Osspial** [comment]
I'll get the new winit release out in the next day or so. However, I expect that this will be the last major version of Winit with `image` integration (see #799, which will get onto master as soon as all the Event Loop 2.0 backends are done). I'd suggest migrating to [`Icon::from_rgba`](https://docs.rs/winit/0.18.1/winit/struct.Icon.html#method.from_rgba) sooner rather than later, which will untie you from any specific version of the `image` crate.

**Comment by paulrouget** [comment]
@Osspial thank you! We will migrate to `from_rgba` after this update. We will also need a glutin update: https://github.com/tomaka/glutin/issues/1114
