### ISSUE TITLE
Port to the latest sctk 0.6.0

### ISSUE THREAD

**Issue by eclipseo** [tomaka/winit#813]
Much API changes. It would help distro packagers to have the latest version.

Thanks.

**Comment by Osspial** [comment]
Thanks for the report!

We're aware of this, and @vberger has actually done the work to fix this! That work was merged in #790, and will land on master once all the desktop backends for [EventLoop 2.0](https://github.com/tomaka/winit/issues/459) are complete. In light of that, I'm going to close this issue.

Unfortunately we don't have a timeline for getting those changes onto crates.io, since afaik no-one is currently working on the new X11 backend and work on the macOS backend has stalled.
